### ISSUE TITLE
ARM64 docker image

### ISSUE THREAD

**Issue by k3v1nwrld** [asdfzxcvbn/update-notifier#10]
Hey could you please add an ARM64 docker image for this project?? I've tried running it locally, but keep getting this weird error that says that my I haven't added my db / bot token / channel id even though i've wrote everything correctly in the .env file. Thanks!

**Comment by asdfzxcvbn** [comment]
can you show your docker-compose file

**Comment by k3v1nwrld** [comment]
> Quote reply

```
version: "3.8"

services:
  update-notifier:
    image: ghcr.io/asdfzxcvbn/update-notifier:main
    restart: unless-stopped
    container_name: update-notifier
    environment:
      DATABASE: /data.db
      BOT_TOKEN: "6097140980:AAHrjWCNyFrxgtC1neHkRVhF0-3s57xxxxx"
      CHANNEL_ID: "20697xxxxx"
    volumes:
      - ./data.db:/data.db
```
